name: "Cloudflare Pages GitHub Action by Phojie"
description: "Publish to Cloudflare Pages"
branding:
  icon: "upload-cloud"
  color: "orange"
inputs:
  apiToken:
    description: "Cloudflare API Token"
    required: true
  accountId:
    description: "Cloudflare Account ID"
    required: true
  projectName:
    description: "The name of the Pages project to upload to"
    required: true
  directory:
    description: "The directory of static assets to upload"
    required: true
  gitHubToken:
    description: "GitHub Token"
    required: false
  branch:
    description: "The name of the branch you want to deploy to"
    required: false
  workingDirectory:
    description: "The working directory in which to run Wrangler"
    required: false
  wranglerVersion:
    description: "The version of Wrangler to use"
    required: false
    default: "2"
  debug:
    description: "Enable debug mode for additional logging"
    required: false
    default: "false"
  timezone:
    description: "Timezone for timestamps in deployment comments (e.g., 'UTC', 'America/New_York', 'Asia/Tokyo')"
    required: false
    default: "UTC"
  appId:
    description: "GitHub App ID (to use a GitHub App instead of a token for custom avatars in comments)"
    required: false
  privateKey:
    description: "GitHub App private key (Base64 encoded)"
    required: false
  installationId:
    description: "GitHub App installation ID"
    required: false
  reactions:
    description: "List of reactions to add to comments (separated by newlines)"
    required: false
runs:
  using: "node16"
  main: "index.js"
